### ISSUE TITLE
cannot import name 'Bot' from 'marvin'

### ISSUE THREAD

**Issue by JT-Apps** [aastroza/live-chat#1]
```
Traceback (most recent call last):
  File "/Users/jet/ai-podcast-generator/podcast.py", line 1, in <module>
    from src.chat import ChatBot
  File "/Users/jet/ai-podcast-generator/src/chat.py", line 1, in <module>
    from marvin import Bot
ImportError: cannot import name 'Bot' from 'marvin' (/opt/miniconda3/envs/ai-podcast-generator/lib/python3.10/site-packages/marvin/__init__.py)

```
Hi, your project is exactly what I am looking for for a project but running into this issue above... Any idea? Does this project still/even use Marvin? I thought it used OpenAI API for text but maybe that's something else? Have tried fiddling around but reached my knowledge limitation and thought I'd ask -- thanks!

**Comment by BronsonN** [comment]
I am trying to help some ditzy blonde use this.....shes a friend. I am getting the same error. It appears this guy hasn't kept his repo/VM up to date(honestly cant blame the guy) and the version of the python is out of date and cannot install marvin.

I will work on it this weekend and see if I can resolve this issue, his vm currently has python 3.8 but I think marvin requires 3.10 of python

we will see what happens

**Comment by BronsonN** [comment]
I got the same error, and I was able to determine that the version of Marvin that was used when this project was created was an older version then is downloaded from the requirements.txt. It seems a lot of refactoring was done to the Marvin repo since this project was built.

I was able to resolve this issue by reverting the marvin version installed from 2.3.7 to 0.9.0. The import statement causing the error was looking for a package called Bot which would then be used to create the ChatBot in chat.py. This package seems to have been renamed/refactored so its not being recognized anymore.

But it looks like there are even more dependency issues after I resolved this.

Im wondering if this project works anymore honestly. My friend wanted to use this so I was trying to help her, but it might be a lost cause at the moment.

**Comment by aastroza** [comment]
Hi! You're right, the project is quite outdated. I haven't had a chance to update everything, and since things change so quickly, it's fallen behind. I'm planning to work on a new version and should have an update ready in the next couple of weeks.
